#!/usr/bin/env php
<?php
set_time_limit(0);
ini_set('memory_limit', '128M');
date_default_timezone_set("Europe/Prague");
require_once __DIR__."/bin/Util/ClassLoader.php";
$data_dir = __DIR__."/data";
$loader_object = new \Util\ClassLoader(__DIR__."/bin",__DIR__."/plugin");
$loader_object->register();
$error_handler = new \Util\ErrorHandler();
$error_handler->register();
declare(ticks = 1);
\pcntl_signal(\SIGTERM,"\Util\Shutdown::shutdown");
\pcntl_signal(\SIGINT,"\Util\Shutdown::shutdown");
$server = new \Server(__DIR__."/config.json",$loader_object,$error_handler,$data_dir,__DIR__);
\Util\Shutdown::init($server);
if($server->isLoadedConfig()){
 $server->loadPlugins();
 if($server->loadVhosts()){
  if($server->run()){
   $server->handleClients();
  }
 }
 $server->stop();
}
